### PR TITLE
Restore GDAS-validation functionality

### LINKED ISSUE #110: Update GDAS-validation to work with GDASApp and g-w updates
GDAS-validation no longer works because GDASApp and g-w have recent changes which have not yet been incorporated into GDAS-validation.  This issue is opened to document the changes required to restore GDAS-validation functionality.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
GDAS-validation no longer works due to GDASApp and g-w updates.  This PR updates GDAS-validation so that it works with the current GDASApp and g-w.

Fixes #110

### CODE REVIEW

**Review by CoryMartin-NOAA — DISMISSED** [review]
Looks good, approve pending successful Hera test. Thanks @RussTreadon-NOAA for this important, but tedious, PR

**Comment by RussTreadon-NOAA** [comment]
Install fresh clone of `RussTreadon-NOAA:feature/jinja_fix` on Hera and Orion.  Execute `setup_workspace.sh` with `-c`, `-b`, and `-s` options.  GDAS-validation jobs run to completion on Hera and Orion.  
- GSI GDAS-validation jobs run are prep, anal, and analdiag
- JEDI GDAS-validation jobs run are prep prepatmiodaobs, atmanlinit, atmanlrun, and atmanlfinal.

Two reminders for Hera
1. set `machine` to `hera` in `setup_workspace.sh` prior to executing the script
2. set `EXPDIR` to valid path in `config_example_gsi.sh` and `config_example_jedi.sh` before executing `setup_workspace.sh -s`

**Comment by RussTreadon-NOAA** [comment]
@xincjin-NOAA , @XuanliLi-NOAA :  do either of you have time to review this PR?  We can merge into `develop` once we have a review and approval.

**Comment by XuanliLi-NOAA** [comment]
Let me try it on Orion. I just did
git clone https://github.com/RussTreadon-NOAA/JEDI-T2O.git
then 
git checkout feature/jinja_fix. Is that correct?

**Comment by RussTreadon-NOAA** [comment]
Yes @XuanliLi-NOAA .  You are correct `git checkout feature/jinja_fix` pulls out a working copy of `feature/jinja_fix`.  This is the branch to use if you want to run a test as part of your review.

**Comment by XuanliLi-NOAA** [comment]
Clone, build and setup for the experiments are successful. 
gdasprep and gdasprepatmiodaobs are successful.
However, the following error occurred when running gdasatmanlinit on Orion:

_^[[38;5;226m2024-03-18 11:13:21,730 - WARNING  - analysis    : Linking is not permitted per EE2.^[[0m
^[[38;21m2024-03-18 11:13:21,731 - INFO     - analysis    :   END: pygfs.task.analysis.link_jediexe^[[0m
^[[38;5;39m2024-03-18 11:13:21,731 - DEBUG    - analysis    :  returning: None^[[0m
Traceback (most recent call last):
  File "/work2/noaa/da/xuanli/e2e_test7/gdas-validation/global-workflow/scripts/exglobal_atm_analysis_initialize.py", line 24, in <module>
    AtmAnl.initialize()
  File "/work2/noaa/da/xuanli/e2e_test7/gdas-validation/global-workflow/ush/python/wxflow/logger.py", line 266, in wrapper
    retval = func(*args, **kwargs)
  File "/work2/noaa/da/xuanli/e2e_test7/gdas-validation/global-workflow/ush/python/pygfs/task/atm_analysis.py", line 74, in initialize
    logger.info(f"Staging CRTM fix files from {self.task_config.CRTM_FIX_YAML}")
  File "/work2/noaa/da/xuanli/e2e_test7/gdas-validation/global-workflow/ush/python/wxflow/attrdict.py", line 79, in __getattr__
    return self.__getitem__(item)
  File "/work2/noaa/da/xuanli/e2e_test7/gdas-validation/global-workflow/ush/python/wxflow/attrdict.py", line 84, in __missing__
    raise KeyError(name)
KeyError: 'CRTM_FIX_YAML'
JGLOBAL_ATM_ANALYSIS_INITIALIZE[1]: postamble JGLOBAL_ATM_ANALYSIS_INITIALIZE 1710778386 1
preamble.sh[70]: set +x
End JGLOBAL_ATM_ANALYSIS_INITIALIZE at 16:13:21 with error code 1 (time elapsed: 00:00:15)_

Here is the log file on Orion: _/work2/noaa/da/xuanli/e2e_test7/gdas-validation/comroot/gdas_eval_gnssro_JEDI/logs/2021080100/gdasatmanlinit.log_.

Xin also tested it on Orion and got the same error message.

**Comment by RussTreadon-NOAA** [comment]
Interesting and frustrating. I ran a successful test on Orion 3/18 morning.  At that time g-w `develop` was at [a5f24951](https://github.com/NOAA-EMC/global-workflow/commit/a5f24951c5bef142747c6f6cc6abd474f0b53ac2).  g-w `develop`was updated twice this morning.  My guess is that [3ccffeee](https://github.com/NOAA-EMC/global-workflow/commit/3ccffeee120340ab580fc9d96b552970c9f42a8f) contains changes which require corresponding GDASApp updates.

**Comment by CoryMartin-NOAA** [comment]
Indeed,:
```
export CRTM_FIX_YAML="${PARMgfs}/gdas/atm_crtm_coeff.yaml.j2"
export JEDI_FIX_YAML="${PARMgfs}/gdas/atm_jedi_fix.yaml.j2"
```

**Comment by RussTreadon-NOAA** [comment]
@XuanliLi-NOAA and @xincjin-NOAA:   I manually tested [cdfb9f1](https://github.com/NOAA-EMC/JEDI-T2O/pull/111/commits/cdfb9f13a34769a7f96110738aeca4e271c2e244) on Hera.  `gdasatmanlinit` ran to completion.  I am now setting up a new test on Orion.

**Comment by XuanliLi-NOAA** [comment]
Thank you, Russ. Let me know when it's ready.

**Comment by RussTreadon-NOAA** [comment]
You can test now on Orion.  The Hera test passed.

**Comment by XuanliLi-NOAA** [comment]
gdasatmanlinit completes successfully on Orion.

**Comment by RussTreadon-NOAA** [comment]
Thank you @XuanliLi-NOAA for the update.  My `gdasatmanlinit` also just finished with `rc=0` on Orion.  `gdasatmanlrun` is now running.

**Comment by XuanliLi-NOAA** [comment]
Both gdasatmanlrun and gdasatmanlfinal completed with error code 0 on Orion.

**Comment by xincjin-NOAA** [comment]
All steps are finished on orion after manually updated that two lines.
Thanks!

**Comment by XuanliLi-NOAA** [comment]
Thank you so much, Russ and Cory.

**Review by XuanliLi-NOAA — APPROVED** [review]
gdas-validation works properly with the changes. Approved.

**Pull request merged**
