### PR TITLE
Merge feature/gdas-validation into develop

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
As GDAS validation nears completion the need for a separate `feature/gdas-validation` diminishes.  This PR brings updates in `feature/gdas-validation` into `develop`.

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , @emilyhcliu , and @ADCollard :  I created this PR as a draft because I don't know the answers to the following questions:
1. Do we want to capture the changes in `feature/gdas-validation` into `develop`?
2. If the answer to 1 is _yes_, is now the right time to merge `feature/gdas-validation` into `develop`?

Based on the answers to these questions, we can delete, pause, or move forward with this PR.

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu and @ADCollard :  any thoughts on this PR?  Keep and move forward or abandon?

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA Let's move forward and merge the feature/gdas-validation branch into the JEDI-T2O.

**Comment by RussTreadon-NOAA** [comment]
Thank you @emilyhcliu and @ADCollard for the green light.  I changed this PR to open and will invite you to be reviewers.

**Review by ADCollard — APPROVED** [review]

**Review by emilyhcliu — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Done!  Thank you @emilyhcliu and @ADCollard for your approvals.  

Developers should use JEDI-T2O `develop`.  I do not plan on making any more updates to `feature/gdas-validation`.  In fact at some point we should delete `feature/gdas-validation`.  There's a button to do so in this PR.

**Pull request merged**
